### ISSUE TITLE
BUG - any path with the string "*temp*" or "*appdata*" will cause the app not to launch

### ISSUE THREAD

**Issue by snaxib** [HunterPie/HunterPie#424] opened 2023-04-25 23:57 UTC
Line 181 of `MainWindow.xaml.cs` calls `VerifyHunterPiePathUseCase`. This executes the following:

`internal class VerifyHunterPiePathUseCase
{

    public static bool Invoke() => !ClientInfo.ClientPath.ToLowerInvariant()
        .ContainsAny(new[] { "temp", "appdata" });

}`

This uses greedy matching, meaning if you have `temp` or `appdata` anywhere in the path, you cannot launch the mod. Example:
`C:\Users\tempo\Desktop\HunterPie` will cause the GUI initialization to fail, stating that you are launching from an unsafe directory.

A workaround is to move the execution directory to any path that does not contain either string.

**Comment by Haato3o** [comment] 2023-04-26 02:50
I already know that, also a duplicate of #354

**Closed** 2023-04-26 02:51 UTC
